line_to_bus_file: /.../rcp45cooler_ssp3/go/input/line_to_bus_csv/line_to_bus.csv
ba_to_ba_hurdle_scaled_file: /.../rcp45cooler_ssp3/go/input/ba_to_ba_hurdle_scaled_csv/BA_to_BA_hurdle_scaled.csv
ba_to_ba_transmission_matrix_file: /.../rcp45cooler_ssp3/go/input/ba_to_ba_transmission_matrix_csv/BA_to_BA_transmission_matrix.csv
lost_capacity_file: /.../rcp45cooler_ssp3/go/input/lost_capacity_csv/lost_capacity_2020.csv
line_parameters_file: /.../rcp45cooler_ssp3/go/input/line_parameters_csv/2050/line_param_2050TC.csv
generator_matrix_file: /.../rcp45cooler_ssp3/go/input/generator_matrix_mat/2050/gen_mat_2050PI.csv
must_run_file: /.../rcp45cooler_ssp3/go/input/must_run_csv/2050/must_run_2050PI.csv
generator_parameters_file: /.../rcp45cooler_ssp3/go/input/generator_parameters_csv/2050/data_genparams_2050PI.csv
generator_outage_file: /.../rcp45cooler_ssp3/go/input/generator_outage_npy/2050/gen_outage_cat_2050PI.npy
thermal_generators_file: /.../rcp45cooler_ssp3/go/input/thermal_generators_csv/2050/thermal_gens_2050PI.csv
fuel_prices_file: /.../rcp45cooler_ssp3/go/input/fuel_prices_csv/2050/fuel_prices_2050PI.csv
daily_hydro_maximum_file: /.../rcp45cooler_ssp3/go/input/daily_hydro_max_csv/hydro_max_2020HG.csv
daily_hydro_minimum_file: /.../rcp45cooler_ssp3/go/input/daily_hydro_min_csv/hydro_min_2020HG.csv
daily_hydro_total_file: /.../rcp45cooler_ssp3/go/input/daily_hydro_total_csv/hydro_total_2020HG.csv
nodal_solar_file: /.../rcp45cooler_ssp3/go/input/nodal_solar_csv/2050/nodal_solar_2050PI_2049RG.csv
nodal_wind_file: /.../rcp45cooler_ssp3/go/input/nodal_wind_csv/2050/nodal_wind_2050PI_2049RG.csv
nodal_offshore_wind_file: /.../rcp45cooler_ssp3/go/input/nodal_offshore_wind_csv/2050/nodal_offshore_wind_2050PI_2049RG.csv
nodal_load_file: /.../rcp45cooler_ssp3/go/input/nodal_load_csv/2050/nodal_load_2049LD.csv
dat_file: /.../rcp45cooler_ssp3/go/input/preprocessor_dat/2050/preprocessor_dat_2050PI_2049RG_2050TC_2049LD.dat
storage_params_file: /.../rcp45cooler_ssp3/go/input/storage_parameters_csv/2050/storage_params_2050PI.csv
bus_to_storage_matrix_file: /.../rcp45cooler_ssp3/go/input/storage_matrix_csv/2050/storage_mat_2050PI.csv
restart_file_directory: /.../rcp45cooler_ssp3/go/input/restart_files/2050
vlt_angle_file: /.../rcp45cooler_ssp3/go/output/native_output/2050/vlt_angle/vlt_angle_2050PI_2049RG_2050TC_2049LD.parquet
mwh_file: /.../rcp45cooler_ssp3/go/output/native_output/2050/mwh/mwh_2050PI_2049RG_2050TC_2049LD.parquet
slack_file: /.../rcp45cooler_ssp3/go/output/native_output/2050/slack/slack_2050PI_2049RG_2050TC_2049LD.parquet
flow_file: /.../rcp45cooler_ssp3/go/output/native_output/2050/flow/flow_2050PI_2049RG_2050TC_2049LD.parquet
duals_file: /.../rcp45cooler_ssp3/go/output/native_output/2050/duals/duals_2050PI_2049RG_2050TC_2049LD.parquet
SoC_file: /.../rcp45cooler_ssp3/go/output/native_output/2050/storage_soc/storage_soc_2050PI_2049RG_2050TC_2049LD.parquet
discharge_file: /.../rcp45cooler_ssp3/go/output/native_output/2050/storage_discharge/storage_discharge_2050PI_2049RG_2050TC_2049LD.parquet
charge_file: /.../rcp45cooler_ssp3/go/output/native_output/2050/storage_charge/storage_charge_2050PI_2049RG_2050TC_2049LD.parquet