node_topology_file: /.../supplementary_data/BA_Topology_Files/10k_Nodes.csv
transmission_subregion_file: /.../supplementary_data/Shapefiles/NERC_Regions/NERC_Regions_Subregions.shp
gen_data_file: /.../rcp45cooler_ssp3/go/input/generator_parameters_csv/2050/data_genparams_2050PI.csv
gen_mat_file_file: /.../rcp45cooler_ssp3/go/input/generator_matrix_mat/2050/gen_mat_2050PI.csv
fuel_price_file: /.../rcp45cooler_ssp3/go/input/fuel_prices_csv/2050/fuel_prices_2050PI.csv
hydro_min_file: /.../rcp45cooler_ssp3/go/input/daily_hydro_min_csv/hydro_min_2020HG.csv
hydro_max_file: /.../rcp45cooler_ssp3/go/input/daily_hydro_max_csv/hydro_max_2020HG.csv
load_input_file: /.../rcp45cooler_ssp3/go/input/nodal_load_csv/2050/nodal_load_2049LD.csv
must_run_input_file: /.../rcp45cooler_ssp3/go/input/must_run_csv/2050/must_run_2050PI.csv
offshore_wind_input_file: /.../rcp45cooler_ssp3/go/input/nodal_offshore_wind_csv/2050/nodal_offshore_wind_2050PI_2049RG.csv
onshore_wind_input_file: /.../rcp45cooler_ssp3/go/input/nodal_wind_csv/2050/nodal_wind_2050PI_2049RG.csv
solar_input_file: /.../rcp45cooler_ssp3/go/input/nodal_solar_csv/2050/nodal_solar_2050PI_2049RG.csv
line_to_bus_input_file: /.../rcp45cooler_ssp3/go/input/line_to_bus_csv/line_to_bus.csv
existing_line_param_file: /.../rcp45cooler_ssp3/go/input/line_parameters_csv/2045/line_param_2045TC.csv
gen_data_output_file: /.../rcp45cooler_ssp3/tep/input/generator_parameters_csv/2050/data_genparams_2050PI.csv
gen_mat_output_file: /.../rcp45cooler_ssp3/tep/input/generator_matrix_mat/2050/gen_mat_2050PI.csv
fuel_price_output_file: /.../rcp45cooler_ssp3/tep/input/monthly_fuel_prices_csv/2050/fuel_prices_monthly_2050PI.csv
hydro_min_output_file: /.../rcp45cooler_ssp3/tep/input/monthly_hydro_min_csv/hydro_min_monthly_2020HG.csv
hydro_max_output_file: /.../rcp45cooler_ssp3/tep/input/monthly_hydro_max_csv/hydro_max_monthly_2020HG.csv
must_run_output_file: /.../rcp45cooler_ssp3/tep/input/monthly_must_run_csv/2050/must_run_monthly_2050PI.csv
load_output_file: /.../rcp45cooler_ssp3/tep/input/monthly_nodal_load_csv/2050/nodal_load_monthly_2049LD.csv
offshore_wind_output_file: /.../rcp45cooler_ssp3/tep/input/monthly_nodal_offshore_wind_csv/2050/nodal_offshore_wind_monthly_2050PI_2049RG.csv
onshore_wind_output_file: /.../rcp45cooler_ssp3/tep/input/monthly_nodal_wind_csv/2050/nodal_offshore_wind_monthly_2050PI_2049RG.csv
solar_output_file: /.../rcp45cooler_ssp3/tep/input/monthly_nodal_solar_csv/2050/nodal_solar_monthly_2050PI_2049RG.csv
line_to_bus_output_file: /.../rcp45cooler_ssp3/tep/input/line_to_bus_csv/line_to_bus.csv
existing_line_param_output_file: /.../rcp45cooler_ssp3/tep/input/line_parameters_csv/2050/line_param_2045TC.csv
tep_output_thermal_gen_file: /.../rcp45cooler_ssp3/tep/output/native_output/2050/Thermal_Gen.csv
tep_output_solar_gen_file: /.../rcp45cooler_ssp3/tep/output/native_output/2050/Solar_Gen.csv
tep_output_wind_gen_file: /.../rcp45cooler_ssp3/tep/output/native_output/2050/Wind_Gen.csv
tep_output_offshore_wind_gen_file: /.../rcp45cooler_ssp3/tep/output/native_output/2050/OffshoreWind_Gen.csv
tep_output_hydro_gen_file: /.../rcp45cooler_ssp3/tep/output/native_output/2050/Hydro_Gen.csv
tep_output_unserved_energy_file: /.../rcp45cooler_ssp3/tep/output/native_output/2050/Unserved_Energy.csv
tep_output_volt_angle_file: /.../rcp45cooler_ssp3/tep/output/native_output/2050/Voltage_Angle.csv
tep_output_power_flow_file: /.../rcp45cooler_ssp3/tep/output/native_output/2050/Power_Flow.csv
tep_output_new_transmission_file: /.../rcp45cooler_ssp3/tep/output/native_output/2050/New_Transmission_Data.csv
tep_output_line_params_file: /.../rcp45cooler_ssp3/tep/output/native_output/2050/line_params_2050TC.csv
go_input_line_params_file: /.../rcp45cooler_ssp3/go/input/line_parameters_csv/2050/line_param_2050TC.csv
interregional_tep_penalty: 0
line_len_security_scalar: 30
apply_budget_bool: false
